# ============================================================
# Shoppy Backend — Terraform Deployment on GCP
# ============================================================
# Resources created:
#   - Static external IP address
#   - Firewall rules (SSH port 22, API port 8080)
#   - Compute Engine VM (e2-small, Ubuntu 22.04)
#   - Startup script that installs Docker, clones code, runs app
# ============================================================

# ── Static External IP ────────────────────────────────────
resource "google_compute_address" "shoppy_ip" {
  name   = "shoppy-backend-ip"
  region = var.region
}

# ── Firewall: Allow SSH (port 22) ─────────────────────────
resource "google_compute_firewall" "allow_ssh" {
  name    = "shoppy-allow-ssh"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["shoppy-backend"]
}

# ── Firewall: Allow API traffic (port 8080) ───────────────
resource "google_compute_firewall" "allow_api" {
  name    = "shoppy-allow-api"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["8080"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["shoppy-backend"]
}

# ── Compute Engine VM ─────────────────────────────────────
resource "google_compute_instance" "shoppy_vm" {
  name         = "shoppy-backend-vm"
  machine_type = var.machine_type
  zone         = var.zone
  tags         = ["shoppy-backend"]

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2204-lts"
      size  = 20
      type  = "pd-standard"
    }
  }

  network_interface {
    network = "default"
    access_config {
      nat_ip = google_compute_address.shoppy_ip.address
    }
  }

  # Pass config as instance metadata (read in startup script)
  metadata = {
    DB_USER       = var.db_user
    DB_PASSWORD   = var.db_password
    DB_NAME       = var.db_name
    REPO_URL      = var.repo_url
    GITHUB_TOKEN  = var.github_token
    GITHUB_BRANCH = var.github_branch

    # Startup script runs once when the VM first boots
    startup-script = file("${path.module}/scripts/startup.sh")
  }

  # Allow the VM to access GCP services (Cloud Logging etc.)
  service_account {
    scopes = ["cloud-platform"]
  }

  labels = {
    environment = "production"
    app         = "shoppy-backend"
  }
}

# ── Write BASE_URL into Android local.properties ─────────
# After `terraform apply`, this file is updated automatically so that
# the next Gradle build picks up the correct server IP without any
# manual edits. local.properties is gitignored, so it's safe to store
# the IP here.
local "android_sdk_dir" {
  # Read the existing sdk.dir line so we don't clobber it
  value = try(
    trimspace(regex("sdk\\.dir=([^\n]+)", file("${path.module}/../../local.properties"))[0]),
    ""
  )
}

resource "local_file" "android_local_properties" {
  filename = "${path.module}/../../local.properties"

  content = <<-EOT
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
sdk.dir=${local.android_sdk_dir}

# -- Injected by Terraform --
# BASE_URL is read by shoppy-mobile/build.gradle.kts at build time.
# Re-run `terraform apply` whenever the server IP changes.
BASE_URL=http://${google_compute_address.shoppy_ip.address}:8080/api/v1/
EOT
}
